"""add active orders count

Revision ID: 42c36ae3bf86
Revises: 0ce2bfad58fc
Create Date: 2026-04-13 15:36:16.956779
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '42c36ae3bf86'
down_revision: Union[str, Sequence[str], None] = '0ce2bfad58fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_order_bids_created_at'), 'order_bids', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)

    if is_sqlite:
        with op.batch_alter_table('orders', recreate='always') as batch_op:
            batch_op.drop_column('selected_bid_id')
    else:
        op.alter_column('feedback', 'feedback',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=500),
                   existing_nullable=False)
        op.alter_column('menu_items', 'price',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   type_=sa.Numeric(precision=10, scale=2),
                   existing_nullable=False)
        op.alter_column('order_bids', 'amount',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   type_=sa.Numeric(precision=10, scale=2),
                   existing_nullable=False)
        op.alter_column('order_items', 'unit_price',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   type_=sa.Numeric(precision=10, scale=2),
                   existing_nullable=False)
        op.alter_column('orders', 'status',
                   existing_type=postgresql.ENUM('CREATED', 'BIDDING', 'BID_ACCEPTED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELED', name='orderstatus'),
                   type_=sa.Enum('CREATED', 'BIDDING', 'BID_ACCEPTED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='order_status_enum'),
                   existing_nullable=False)
        op.alter_column('orders', 'total_amount',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   type_=sa.Numeric(precision=10, scale=2),
                   existing_nullable=False)
        op.drop_constraint(op.f('orders_selected_bid_id_fkey'), 'orders', type_='foreignkey')
        op.drop_column('orders', 'selected_bid_id')

    op.add_column('reports', sa.Column('comment', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('active_orders_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('active_orders_for_delivery_count', sa.Integer(), nullable=False, server_default='0'))
    if not is_sqlite:
        op.alter_column('users', 'active_orders_count', server_default=None)
        op.alter_column('users', 'active_orders_for_delivery_count', server_default=None)
    op.add_column('users', sa.Column('about_me', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('upi_screenshot_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))

    if not is_sqlite:
        op.alter_column('users', 'department',
                   existing_type=sa.VARCHAR(length=120),
                   type_=sa.Enum('CSE', 'IT', 'IOT', 'ECE', 'MECH', 'CIVIL', 'CHEMICAL', 'AIML', 'AIDS', 'CYBER', 'EEE', 'EIE', 'BME', 'MBA', 'OTHERS', name='departments'),
                   existing_nullable=False)
        op.alter_column('users', 'register_number',
                   existing_type=sa.VARCHAR(length=60),
                   type_=sa.String(length=12),
                   existing_nullable=False)

    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_users_register_number'), 'users', ['register_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_register_number'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')

    if not is_sqlite:
        op.alter_column('users', 'register_number',
                   existing_type=sa.String(length=12),
                   type_=sa.VARCHAR(length=60),
                   existing_nullable=False)
        op.alter_column('users', 'department',
                   existing_type=sa.Enum('CSE', 'IT', 'IOT', 'ECE', 'MECH', 'CIVIL', 'CHEMICAL', 'AIML', 'AIDS', 'CYBER', 'EEE', 'EIE', 'BME', 'MBA', 'OTHERS', name='departments'),
                   type_=sa.VARCHAR(length=120),
                   existing_nullable=False)

    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'upi_screenshot_url')
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'active_orders_for_delivery_count')
    op.drop_column('users', 'active_orders_count')
    op.drop_column('reports', 'comment')

    if is_sqlite:
        with op.batch_alter_table('orders', recreate='always') as batch_op:
            batch_op.add_column(sa.Column('selected_bid_id', sa.INTEGER(), nullable=True))
    else:
        op.add_column('orders', sa.Column('selected_bid_id', sa.INTEGER(), autoincrement=False, nullable=True))
        op.create_foreign_key(op.f('orders_selected_bid_id_fkey'), 'orders', 'order_bids', ['selected_bid_id'], ['id'], ondelete='SET NULL')

    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')

    if not is_sqlite:
        op.alter_column('orders', 'total_amount',
                   existing_type=sa.Numeric(precision=10, scale=2),
                   type_=sa.DOUBLE_PRECISION(precision=53),
                   existing_nullable=False)
        op.alter_column('orders', 'status',
                   existing_type=sa.Enum('CREATED', 'BIDDING', 'BID_ACCEPTED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='order_status_enum'),
                   type_=postgresql.ENUM('CREATED', 'BIDDING', 'BID_ACCEPTED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELED', name='orderstatus'),
                   existing_nullable=False)
        op.alter_column('order_items', 'unit_price',
                   existing_type=sa.Numeric(precision=10, scale=2),
                   type_=sa.DOUBLE_PRECISION(precision=53),
                   existing_nullable=False)

    op.drop_index(op.f('ix_order_bids_created_at'), table_name='order_bids')

    if not is_sqlite:
        op.alter_column('order_bids', 'amount',
                   existing_type=sa.Numeric(precision=10, scale=2),
                   type_=sa.DOUBLE_PRECISION(precision=53),
                   existing_nullable=False)
        op.alter_column('menu_items', 'price',
                   existing_type=sa.Numeric(precision=10, scale=2),
                   type_=sa.DOUBLE_PRECISION(precision=53),
                   existing_nullable=False)

    op.drop_column('hotels', 'description')

    if not is_sqlite:
        op.alter_column('feedback', 'feedback',
                   existing_type=sa.String(length=500),
                   type_=sa.TEXT(),
                   existing_nullable=False)
    # ### end Alembic commands ###
