"""add_ondelete_constraints_to_order_relationships

Revision ID: 4b74212dd106
Revises: 20260330_0003
Create Date: 2026-03-31 12:02:54.800997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4b74212dd106'
down_revision: Union[str, Sequence[str], None] = '20260330_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)

    # Drop dependent report message reference before dropping discussion_messages
    if is_sqlite:
        op.drop_index(op.f('ix_reports_message_id'), table_name='reports')
        with op.batch_alter_table('reports', recreate='always') as batch_op:
            batch_op.drop_column('message_id')
    else:
        op.drop_index(op.f('ix_reports_message_id'), table_name='reports')
        op.drop_constraint(op.f('reports_message_id_fkey'), 'reports', type_='foreignkey')
        op.drop_column('reports', 'message_id')
    
    # Now it's safe to drop discussion_messages
    op.drop_index(op.f('ix_discussion_messages_channel_date'), table_name='discussion_messages')
    op.drop_index(op.f('ix_discussion_messages_user_id'), table_name='discussion_messages')
    op.drop_table('discussion_messages')
    
    # Update order relationships for non-SQLite backends.
    if not is_sqlite:
        op.drop_constraint(op.f('order_bids_order_id_fkey'), 'order_bids', type_='foreignkey')
        op.create_foreign_key(None, 'order_bids', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('orders_selected_bid_id_fkey'), 'orders', type_='foreignkey')
        op.create_foreign_key(None, 'orders', 'order_bids', ['selected_bid_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite:
        with op.batch_alter_table('reports', recreate='always') as batch_op:
            batch_op.add_column(sa.Column('message_id', sa.INTEGER(), nullable=True))
    else:
        op.add_column('reports', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False))
        op.create_foreign_key(op.f('reports_message_id_fkey'), 'reports', 'discussion_messages', ['message_id'], ['id'])
        op.create_index(op.f('ix_reports_message_id'), 'reports', ['message_id'], unique=False)
        op.drop_constraint(None, 'orders', type_='foreignkey')
        op.create_foreign_key(op.f('orders_selected_bid_id_fkey'), 'orders', 'order_bids', ['selected_bid_id'], ['id'])
        op.drop_constraint(None, 'order_bids', type_='foreignkey')
        op.create_foreign_key(op.f('order_bids_order_id_fkey'), 'order_bids', 'orders', ['order_id'], ['id'])
    op.create_table('discussion_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('channel_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('discussion_messages_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('discussion_messages_pkey'))
    )
    op.create_index(op.f('ix_discussion_messages_user_id'), 'discussion_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_discussion_messages_channel_date'), 'discussion_messages', ['channel_date'], unique=False)
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
