"""Add academic fields to user

Revision ID: db02c77fdc89
Revises: 42c36ae3bf86
Create Date: 2026-07-17 12:49:33.124858
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'db02c77fdc89'
down_revision: Union[str, Sequence[str], None] = '42c36ae3bf86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'feedback',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.create_unique_constraint(None, 'hotels', ['name'])
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.create_foreign_key(None, 'hotels', 'users', ['manager_id'], ['id'])
    op.alter_column('menu_items', 'price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'hotels', ['hotel_id'], ['id'])
    op.alter_column('order_bids', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('order_bids', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'ORDER_CANCELLED', name='bidstatus'),
               existing_nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.alter_column('orders', 'total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['reporter_id'], ['id'])
    op.drop_index(op.f('ix_terms_and_conditions_is_active'), table_name='terms_and_conditions')
    op.drop_index(op.f('ix_terms_and_conditions_version'), table_name='terms_and_conditions')
    op.create_index(op.f('ix_terms_and_conditions_version'), 'terms_and_conditions', ['version'], unique=True)
    op.add_column('users', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('section', sa.String(length=10), nullable=True))
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Enum('CSE', 'IT', 'IOT', 'ECE', 'MECH', 'CIVIL', 'CHEMICAL', 'AIML', 'AIDS', 'CYBER', 'EEE', 'EIE', 'BME', 'MBA', 'OTHERS', name='departments'),
               existing_nullable=False)
    op.alter_column('users', 'register_number',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'register_number',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.alter_column('users', 'department',
               existing_type=sa.Enum('CSE', 'IT', 'IOT', 'ECE', 'MECH', 'CIVIL', 'CHEMICAL', 'AIML', 'AIDS', 'CYBER', 'EEE', 'EIE', 'BME', 'MBA', 'OTHERS', name='departments'),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('users', 'section')
    op.drop_column('users', 'semester')
    op.drop_column('users', 'year')
    op.drop_index(op.f('ix_terms_and_conditions_version'), table_name='terms_and_conditions')
    op.create_index(op.f('ix_terms_and_conditions_version'), 'terms_and_conditions', ['version'], unique=False)
    op.create_index(op.f('ix_terms_and_conditions_is_active'), 'terms_and_conditions', ['is_active'], unique=False)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['reporter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('order_bids', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'ORDER_CANCELLED', name='bidstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('order_bids', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('menu_items', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.create_foreign_key(None, 'hotels', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'hotels', type_='unique')
    op.alter_column('feedback', 'feedback',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
